Repository sparta-incubating/rchive-front-archive, pull requests merged in 2024-09, with the labels that each got.

#18 Feat/user info with header
  package.json
  src/api/client/authApi.ts
  src/api/server/authApi.ts
  src/api/server/postsApi.ts
  src/app/(rootLayout)/(home)/page.tsx
  src/app/(rootLayout)/layout.tsx
  src/auth.ts
  src/components/atoms/post/postThumbnail.tsx
  src/components/atoms/profile/profileDropDown.tsx
  src/components/atoms/profile/profileDropDownItem.tsx
  src/components/atoms/profile/profileDropDownMenu.tsx
  src/components/molecules/post/postCard.tsx
  src/components/molecules/profile/headerProfileContainer.tsx
  src/components/organisms/postList/postListContainer.tsx
  src/components/pages/customError.tsx
  src/components/pages/mainPage.tsx
  src/components/pages/postList.tsx
  src/components/pages/signIn.tsx
  src/constatns/posts.constant.ts
  src/hooks/useSearchKeyword.ts
  src/hooks/useSearchTutor.ts
  src/hooks/useServerComponentErrorHandling.ts
  src/middleware.ts
  src/provider/compoundProvider.tsx
  src/redux/slice/auth.slice.ts
  src/types/auth.types.ts
  src/types/next-auth.d.ts
  src/types/posts.types.ts
  src/utils/setAuthInfo/setAuthInfo.tsx
  yarn.lock
Labels: enhancement

#19 Feat/post list with filter
  src/api/client/postApi.ts
  src/api/server/postsApi.ts
  src/app/(rootLayout)/(home)/page.tsx
  src/auth.ts
  src/components/atoms/category/categoryDropDown.tsx
  src/components/atoms/category/categoryTabMenu.tsx
  src/components/atoms/post/postThumbnail.tsx
  src/components/atoms/post/postTitle.tsx
  src/components/atoms/searchInput/searchInputDropDownItem.tsx
  src/components/atoms/searchInput/searchInputDropDownItemCard.tsx
  src/components/molecules/categoryGroup/categoryGroup.tsx
  src/components/molecules/categorySelector.tsx
  src/components/molecules/post/postCard.tsx
  src/components/molecules/searchInput/searchInputContainer.tsx
  src/components/molecules/subCategoryGroup/subCategoryGroup.tsx
  src/components/organisms/postList/postListContainer.tsx
  src/components/organisms/searchInput.tsx
  src/components/pages/emptyPage.tsx
  src/components/pages/mainPage.tsx
  src/components/pages/postList.tsx
  src/constatns/post.constant.ts
  src/constatns/posts.constant.ts
  src/hooks/usePostList.ts
  src/hooks/useRecentSearchHistory.ts
  src/hooks/useServerComponentErrorHandling.ts
  src/types/posts.types.ts
  tailwind.config.ts
Labels: enhancement

#21 fix: header user info
  src/auth.ts
  src/components/molecules/profile/headerProfileContainer.tsx
  src/utils/setAuthInfo/post.util.ts
Labels: bug, enhancement

#26 Feat/post detail
  package.json
  src/api/server/postsApi.ts
  src/api/signup/keys.constant.ts
  src/app/(rootLayout)/(home)/page.tsx
  src/app/(rootLayout)/post/[id]/page.tsx
  src/app/api/auth/reissue/route.ts
  src/app/api/notion/page.tsx
  src/app/api/notion/page/route.ts
  src/components/atoms/postDetail/postDetailHeaderCategory.tsx
  src/components/atoms/postDetail/postDetailHeaderText.tsx
  src/components/atoms/postDetail/socialButton.tsx
  src/components/molecules/footer.tsx
  src/components/molecules/form/PhoneField.tsx
  src/components/molecules/post/postCard.tsx
  src/components/molecules/postDetail/morePost.tsx
  src/components/molecules/postDetail/notionContainer.tsx
  src/components/molecules/postDetail/notionLink.tsx
  src/components/molecules/postDetail/postDetailCategoryGroup.tsx
  src/components/molecules/postDetail/postDetailHeader.tsx
  src/components/molecules/postDetail/postDetailTag.tsx
  src/components/molecules/postDetail/socialButtonGroup.tsx
  src/components/molecules/postDetail/videoContainer.tsx
  src/components/molecules/profile/headerProfileContainer.tsx
  src/components/molecules/tagCard.tsx
  src/components/organisms/postList/postListContainer.tsx
  src/components/organisms/postList/previewContainer.tsx
  src/components/organisms/searchInput.tsx
  src/components/pages/detailPage.tsx
  src/components/pages/postDetailPage.tsx
  src/hooks/usePostList.ts
  src/hooks/useRecentSearchHistory.ts
  src/hooks/useSocialButtonPosition.ts
  src/middleware.ts
  src/provider/compoundProvider.tsx
  src/types/posts.types.ts
  src/utils/nextOptions/nextAuth.util.ts
  src/utils/notionAPI.ts
  yarn.lock
Labels: enhancement, style, feat

#32 Fix/tag api
  src/app/(rootLayout)/tag/page.tsx
  src/components/pages/postList.tsx
  src/components/pages/postListForTag.tsx
  src/hooks/usePostList.ts
  src/hooks/usePostListForTag.ts
  src/hooks/useQueryParams.ts
Labels: bug, enhancement

#34 [#10] refactor: ci 설정
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .idea/.name
Labels: enhancement

#49 fix: post detail back button 오류수정
  src/components/molecules/postDetail/postDetailHeader.tsx
Labels: bug, enhancement

#54 [#53] update : category backend data로 변경
  .idea/.name
  src/components/molecules/categoryGroup/categoryGroup.tsx
  src/constatns/post.constant.ts
  src/hooks/usePostList.ts
  src/hooks/usePostTypeNames.ts
Labels: enhancement, update

#56 [#55] update : post list
  src/components/pages/postList.tsx
Labels: enhancement, style, update

#58 update : notion 안내 문구 워딩 변경
  src/components/molecules/postDetail/notionLink.tsx
Labels: enhancement, style, update

#60 update : loginPeriod -> selectPeriod로 변경
  src/api/client/postApi.ts
  src/api/server/postsApi.ts
Labels: enhancement, feat, update

#62 update : tag 검색 변경
  src/app/(rootLayout)/(home)/page.tsx
  src/components/molecules/post/tagNamegroup.tsx
  src/components/molecules/postDetail/postDetailTag.tsx
  src/hooks/usePostList.ts
Labels: enhancement, feat, update

#64 update/youtube-auto-playing
  package.json
  src/components/molecules/postDetail/videoContainer.tsx
  yarn.lock
Labels: enhancement, feat, update

#66 [#65]Update : 닉네임 백엔드에서 자동생성으로 회원가입 로직 수정
  src/app/(rootLayout)/role/result/page.tsx
  src/class/signup.ts
  src/components/molecules/form/PhoneField.tsx
  src/components/molecules/form/PhoneForm.tsx
  src/components/organisms/roleSelectForm.tsx
  src/components/pages/signIn.tsx
  src/components/pages/signUpCompleteModal.tsx
  src/components/pages/signupModal.tsx
  src/hooks/useSignupForm.tsx
  src/validators/auth/signup.validator.ts
Labels: style, update

#68 [#37] Feat : 북마크 기능 구현
  public/assets/icons/bookmark.svg
  public/assets/icons/hover_bookmark.svg
  public/assets/icons/select_bookmark.svg
  public/assets/icons/uis_bookmark.svg
  public/assets/icons/un_bookmark.svg
  src/api/bookmark/bookmarkApi.ts
  src/api/bookmark/keys.constant.ts
  src/api/bookmark/useMutation.ts
  src/api/bookmark/useQuery.ts
  src/app/(rootLayout)/bookmark/page.tsx
  src/app/(rootLayout)/mypage/page.tsx
  src/app/(rootLayout)/role/result/page.tsx
  src/components/atoms/post/bookmarkIcon.tsx
  src/components/atoms/post/postTitle.tsx
  src/components/atoms/profile/profileDropDown.tsx
  src/components/molecules/form/PhonChangeField.tsx
  src/components/molecules/form/PhoneField.tsx
  src/components/molecules/mypageHeader.tsx
  src/components/molecules/post/postCard.tsx
  src/components/organisms/bookmarkInput.tsx
  src/components/pages/bookMarkPage.tsx
  src/components/pages/emptyBookmark.tsx
  src/components/pages/mainPage.tsx
  src/components/pages/profile/phoneChangeModal.tsx
  src/components/pages/signIn.tsx
  src/components/pages/signupModal.tsx
  src/constatns/bookmark.constant.ts
  src/hooks/useSignupForm.tsx
Labels: feat

#70 feat: 문의하기 button 연결
  src/components/atoms/helperButton.tsx
  src/components/pages/roleResult/roleWait.tsx
  src/constatns/helpLink.constant.ts
Labels: enhancement, feat

#72 [#71] feat : 상세 페이지 내에서도 북마크 추가
  src/app/(rootLayout)/post/[id]/page.tsx
  src/components/atoms/InputContainer.tsx
  src/components/atoms/PasswordContainer.tsx
  src/components/molecules/form/PhonChangeField.tsx
  src/components/molecules/post/postCard.tsx
  src/components/molecules/postDetail/postDetailHeader.tsx
  src/components/pages/bookMarkPage.tsx
  src/components/pages/postDetailPage.tsx
  src/components/pages/profile/passwordChangeModal.tsx
  src/components/pages/profile/phoneChangeModal.tsx
Labels: style, feat

#83 [#82] fix: 더보기 버튼 오류 수정
  src/components/molecules/postDetail/morePost.tsx
  src/components/pages/postDetailPage.tsx
Labels: bug, enhancement

#91 [#87]Update : 로그인 대시보드 이미지 수정
  src/components/pages/bookMarkPage.tsx
  src/components/pages/signIn.tsx
  tailwind.config.ts
Labels: style, update

#92 [#73] Fix : 북마크 기능 수정
  src/api/bookmark/useMutation.ts
  src/api/client/authApi.ts
  src/api/server/authApi.ts
  src/app/actions/serverActions.ts
  src/auth.ts
  src/components/molecules/mypageHeader.tsx
  src/components/molecules/post/postCard.tsx
  src/components/molecules/profile/headerProfileContainer.tsx
  src/components/molecules/searchInput/searchInputContainer.tsx
  src/components/molecules/selectTrackAccount.tsx
  src/components/pages/bookMarkPage.tsx
  src/components/pages/myProfile.tsx
  src/components/pages/progressModal.tsx
  src/components/pages/signIn.tsx
  src/middleware.ts
  src/provider/compoundProvider.tsx
  src/redux/slice/auth.slice.ts
  src/types/auth.types.ts
  src/types/next-auth.d.ts
  src/utils/setAuthInfo/setAuthInfo.tsx
Labels: enhancement

#95 [#94] loading progress 적용
  src/components/atoms/modal.tsx
  src/components/molecules/postDetail/notionContainer.tsx
  src/components/pages/bookMarkPage.tsx
  src/components/pages/myProfile.tsx
  src/components/pages/progressModal.tsx
  src/components/pages/selectAccountPage.tsx
  src/middleware.ts
Labels: enhancement, feat

#96 [#93] Fix : 북마크 전체 삭제 모달 문구 수정
  src/api/bookmark/useMutation.ts
  src/components/pages/bookMarkPage.tsx
Labels: bug

#98 [#97] 최근 검색어로 검색 클릭 후 dropdown close 추가
  src/components/organisms/searchInput.tsx
Labels: bug, enhancement, fix

#100 [#99] home에서 filtering 후 detail접속 후 뒤로가기 하면 tutor filter 표기 오류
  src/components/molecules/profile/headerProfileContainer.tsx
  src/hooks/usePostList.ts
Labels: bug, enhancement, fix

#103 [#102] fix:수준별 카테고리 빈 페이지일때 문구 수정 등
  src/components/molecules/categoryGroup/categoryGroup.tsx
  src/components/organisms/searchInput.tsx
  src/components/pages/postList.tsx
Labels: bug, enhancement, fix

#104 [#101] Fix : 마이페이지 UI 수정
  src/components/atoms/profileLayout.tsx
  src/components/pages/myProfile.tsx
Labels: style
